#if defined _command_manager_const_included
    #endinput
#endif
#define _command_manager_const_included

/*******************************************************************************
 * DEFINITIONS
 ******************************************************************************/

#define FLAG_METHOD_SAY      1
#define FLAG_METHOD_SAY_TEAM 2

#define FLAG_STATE_ALIVE     3
#define FLAG_STATE_DEAD      4

#define FLAG_TEAM_UNASSIGNED 5
#define FLAG_TEAM_T          6
#define FLAG_TEAM_CT         7
#define FLAG_TEAM_SPECTATOR  8

#define FLAG_SEPARATOR          ','

#define FLAG_METHOD_SAY_CH      '1'
#define FLAG_METHOD_SAY_TEAM_CH '2'

#define FLAG_STATE_ALIVE_CH     'a'
#define FLAG_STATE_DEAD_CH      'd'

#define FLAG_TEAM_UNASSIGNED_CH 'u'
#define FLAG_TEAM_T_CH          't'
#define FLAG_TEAM_CT_CH         'c'
#define FLAG_TEAM_SPECTATOR_CH  's'