#if defined _zm_modelmanager_const_included
    #endinput
#endif
#define _zm_modelmanager_const_included

/*******************************************************************************
 * DEFINITIONS
 ******************************************************************************/

enum CSI {
    CSI_P228            = CSW_P228,
    CSI_SCOUT           = CSW_SCOUT,
    CSI_HEGRENADE       = CSW_HEGRENADE,
    CSI_XM1014          = CSW_XM1014,
    CSI_C4              = CSW_C4,
    CSI_MAC10           = CSW_MAC10,
    CSI_AUG             = CSW_AUG,
    CSI_SMOKEGRENADE    = CSW_SMOKEGRENADE,
    CSI_ELITE           = CSW_ELITE,
    CSI_FIVESEVEN       = CSW_FIVESEVEN,
    CSI_UMP45           = CSW_UMP45,
    CSI_SG550           = CSW_SG550,
    CSI_GALIL           = CSW_GALIL,
    CSI_FAMAS           = CSW_FAMAS,
    CSI_USP             = CSW_USP,
    CSI_GLOCK18         = CSW_GLOCK18,
    CSI_AWP             = CSW_AWP,
    CSI_MP5NAVY         = CSW_MP5NAVY,
    CSI_M249            = CSW_M249,
    CSI_M3              = CSW_M3,
    CSI_M4A1            = CSW_M4A1,
    CSI_TMP             = CSW_TMP,
    CSI_G3SG1           = CSW_G3SG1,
    CSI_FLASHBANG       = CSW_FLASHBANG,
    CSI_DEAGLE          = CSW_DEAGLE,
    CSI_SG552           = CSW_SG552,
    CSI_AK47            = CSW_AK47,
    CSI_P90             = CSW_P90,
    CSI_SHIELDGUN       = CSW_SHIELDGUN,
    CSI_VEST            = CSW_VEST,
    CSI_VESTHELM        = CSW_VESTHELM,
    CSI_DEFUSER         = 33,
    CSI_NVGS            = 34,
    CSI_PRIAMMO         = 36,
    CSI_SECAMMO         = 37,
};