#if defined _zm_weaponmodel_const_included
    #endinput
#endif
#define _zm_weaponmodel_const_included

/*******************************************************************************
 * DEFINITIONS
 ******************************************************************************/

enum ZM_WEAPON {
    ZM_P228             = CSW_P228,
    ZM_SCOUT            = CSW_SCOUT,
    ZM_HEGRENADE        = CSW_HEGRENADE,
    ZM_XM1014           = CSW_XM1014,
    ZM_C4               = CSW_C4,
    ZM_MAC10            = CSW_MAC10,
    ZM_AUG              = CSW_AUG,
    ZM_SMOKEGRENADE     = CSW_SMOKEGRENADE,
    ZM_ELITE            = CSW_ELITE,
    ZM_FIVESEVEN        = CSW_FIVESEVEN,
    ZM_UMP45            = CSW_UMP45,
    ZM_SG550            = CSW_SG550,
    ZM_GALIL            = CSW_GALIL,
    ZM_FAMAS            = CSW_FAMAS,
    ZM_USP              = CSW_USP,
    ZM_GLOCK18          = CSW_GLOCK18,
    ZM_AWP              = CSW_AWP,
    ZM_MP5NAVY          = CSW_MP5NAVY,
    ZM_M249             = CSW_M249,
    ZM_M3               = CSW_M3,
    ZM_M4A1             = CSW_M4A1,
    ZM_TMP              = CSW_TMP,
    ZM_G3SG1            = CSW_G3SG1,
    ZM_FLASHBANG        = CSW_FLASHBANG,
    ZM_DEAGLE           = CSW_DEAGLE,
    ZM_SG552            = CSW_SG552,
    ZM_AK47             = CSW_AK47,
    ZM_KNIFE            = CSW_KNIFE,
    ZM_P90              = CSW_P90,
    ZM_SHIELDGUN        = CSW_SHIELDGUN,
    ZM_VEST             = CSW_VEST,
    ZM_VESTHELM         = CSW_VESTHELM,
    ZM_DEFUSER          = 33,
    ZM_NVGS             = 34,
    ZM_PRIAMMO          = 36,
    ZM_SECAMMO          = 37,
};